export enum ApiErrors{
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
    REQUEST_SCHEMA_ERROR = 'REQUEST_SCHEMA_ERROR',
    UNAUTHORIZED = 'UNAUTHORIZED',
    NOT_FOUND = 'NOT_FOUND',
    INCORRECT_LOGIN = 'INCORRECT_LOGIN',
    USER_NO_EXISTS = 'USER_NO_EXISTS',
    USER_EXISTS = 'USER_EXISTS',
    BAD_REQUEST = 'BAD_REQUEST',
    FORBIDDEN = 'FORBIDDEN',
    NO_VALID_OPTION = 'NO_VALID_OPTION',
    INVALID_EMAIL = 'INVALID_EMAIL',
    INVALID_PASSWORD = 'INVALID_PASSWORD',
    ITEM_NO_EXISTS = 'ITEM_NO_EXISTS'
}